{
  host,
  inputs,
  pkgs,
  ...
}:

# The single composition point for every host:
#   1. the system capability bundle (modules/system)
#   2. the primary user account
#   3. that user's Home Manager configuration (modules/user)
#
# A host directory under hosts/<name>/ is data only:
#   variables.nix               every machine-specific value
#   hardware-configuration.nix  generated by nixos-generate-config
#   extra.nix                   optional host-local system packages
let
  userName = host.user.name;
in
{
  networking.hostName = host.hostname;

  imports = [
    ../system
  ];

  users.users.${userName} = {
    isNormalUser = true;
    description = host.user.description;
    home = host.user.homeDirectory;
    createHome = true;
    extraGroups = host.user.extraGroups;
    shell = pkgs.zsh;
  };

  # Home Manager is composed here rather than hidden in a root home/<user>
  # tree, so the specialArgs (`host`, `inputs`) reach every user module.
  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    extraSpecialArgs = {
      inherit host inputs;
    };

    users.${userName} = {
      imports = [ ../user ];

      home.username = userName;
      home.homeDirectory = host.user.homeDirectory;
      home.stateVersion = host.stateVersion;
    };
  };
}
